# Install nginx
- name: ensure nginx is at the latest version
  apt: name=nginx state=latest
- name: Setup nginx conf
  template:
    src=../nginx.cfg
    dest=/etc/nginx/sites-enabled/default
- name: start nginx
  service:
      name: nginx
      state: started
